### ISSUE TITLE
Code review by team 45 Heliums

### ISSUE THREAD

**Issue by Oitur** [jalasem/enumerable_methods#2]
Hey Abdul!

So far your code is looking great! The stickler is complaining that you're disabling the module in rubocop (line 3 in your code). As we've discussed earlier, it's not recommended to disable or change things in the stickler, as you won't be solving the problem, but getting around it.

It's also suggested that switch-case statements are better in ruby than if-elsif, so you might want to revise that (for example, in lines 30-41 and so on)

Keep up the good work!

**Comment by jalasem** [comment]
thanks for the insight @Oitur I got it fixed 😊
